teams:
    miway:
        - pierredup
        - royalmitten
        - dhdutoit
        - HendrikGrobler
        - mosekwa
        - smithandre
        - ViGouRCanberra
        - CarmeloNaciti
        - 9tails1
    afrihost:
        - mostertb
