teams:
    miway:
        - pierredup
        - royalmitten
        - dhdutoit
        - HendrikGrobler
        - mosekwa
        - smithandre
        - ViGouRCanberra
        - CarmeloNaciti
        - 9tails1
        - RonIce
        - Malise-Obert
    afrihost:
        - sarelvdwalt
        - mostertb
        - Owkkuri
        - sacheen
        - johnathanmdell
        - awesome-fortune
        - luketruter
        - leepelser
        - Dorfling
        - Syb3r1us
        - prashant8821
        - Sunjalo
        - sanushen
        - derde
