teams:
    miway:
        - pierredup
        - royalmitten
        - dhdutoit
        - HendrikGrobler
        - mosekwa
        - smithandre
        - ViGouRCanberra
    afrihost:
        - mostertb